# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rafl73LweUFngoBD8EPB8feC80M8JTmv
"""

from collections import deque

def solution(n,computers):
    answer = 0
    visited = [0] * n #컴퓨터의 개수만큼 배열의 길이 설정
    
    #탐색할 때 지나간 노드를 visited에 표시한다
    for i in range(n):
        if visited[i]:
            continue
        answer += 1 #탐색되면 1씩 증가
        dq = deque([computers[i]]) #dq를 deque함수를 통해 deque의 형태로 만듬
        while dq:
            nodes = dq.popleft()
            for j in range(n):#탐색하는 동안 visited를 이용하여 지나가지 않은 루트 노드를 만든다.
                if nodes[j] and not visited [j]:
                    dq.append(computers[j])
                    visited[j] = 1
            
    return answer