# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bu-e_4sMeNotDYzEt1ZNoZdqljHTFcX9
"""

def solution(progresses, speeds): # 두 매개변수를 큐로 가정합니다.
    answer = []
    while progresses: # progresses가 비어버릴때 까지 다음을 반복한다
        for i in range(len(progresses)): # progresses의 길이만큼 순회하여 각 속도를 더해준다
            progresses[i] += speeds[i]
            
        cnt = 0 # 점수 추가용
        while progresses and progresses[0] >= 100: 
            progresses.pop(0)
            speeds.pop(0)
            cnt +=1
        if cnt > 0: # 배포된 개수가 0보다 크면 추가한다.
            answer.append(cnt)
    
    return answer