# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bu-e_4sMeNotDYzEt1ZNoZdqljHTFcX9
"""

def solution(s):
    answer = True
    stack = [] # 스택을 활용하여(사실상 빈 리스트) 제대로 된 괄호가 들어갔는지 pop을 통해 확인
    for i in s: # s에 대해 연산 수행
        if i=='(': # "("는 괄호의 시작
            stack.append(i)
        else:
            if stack and stack.pop()=='(': # 스택에도 "(", pop되도 "("면 잘못된 괄호
                continue
            else: # 아니면 제대로 된 괄호
                return False

    return len(stack) == 0