# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pKFHw9-DP27ajf1mne-BF9R7OUlAH67
"""

# 타임에러...for문 두개라 그런듯합니다...
import itertools # 숫자들의 조합을 위해 itertools 사용
def solution(numbers):
    answer = ''
    temp = ''
    numbers = list(map(str, numbers)) # 숫자들을 문자형으로 변형시킴
    result = list(itertools.permutations(numbers, len(numbers))) # 조합들이 저장된 리스트
    temp_list = []

    for i in result: # 순열들 내부의 값들을 합해줌
        for j in range(len(i)): 
            temp = temp + i[j]
        temp_list.append(temp)    
        temp = ''          
    temp_list.sort(reverse = True) # 더해준것이 저장된 리스트를 역으로 sort해주어 최대값을 찾아줌
    answer = temp_list[0]
        
        
    return answer

